[package]
name = "citizensdivided"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
juniper = "0.15.10"
warp = "0.3.2"
tokio = { version = "1.20.1", features = ["full"] }
dotenv = "0.15.0"
reqwest = "0.11.11"
sqlx = { version = "0.6", features = [ "runtime-tokio-rustls", "macros", "postgres" ] }
url = "2.2.2"

[[bin]]
name = "scraping"
