-- Your SQL goes here
CREATE TABLE IF NOT EXISTS members (
    id VARCHAR(255) NOT NULL PRIMARY KEY,
    chamber VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    short_title VARCHAR(255) NOT NULL,
    api_uri VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    middle_name VARCHAR(255),
    last_name VARCHAR(255) NOT NULL,
    suffix VARCHAR(255),
    date_of_birth DATE NOT NULL,
    gender VARCHAR(255) NOT NULL,
    party VARCHAR(255) NOT NULL,
    leadership_role VARCHAR(255),
    twitter_account VARCHAR(255) NOT NULL,
    facebook_account VARCHAR(255),
    youtube_account VARCHAR(255),
    govtrack_id INTEGER NOT NULL,
    cspan_id VARCHAR(255),
    votesmart_id DATE NOT NULL,
    icpsr_id VARCHAR(255),
    crp_id VARCHAR(255) NOT NULL,
    google_entity_id VARCHAR(255) NOT NULL,
    fec_candidate_id VARCHAR(255) NOT NULL,
    url VARCHAR(255) NOT NULL,
    rss_url VARCHAR(255),
    contact_form VARCHAR(255),
    in_office VARCHAR(255) NOT NULL,
    cook_pvi VARCHAR(255),
    dw_nominate VARCHAR(255),
    ideal_point VARCHAR(255),
    seniority INTEGER NOT NULL,
    next_election INTEGER NOT NULL,
    total_votes INTEGER NOT NULL,
    missed_votes INTEGER NOT NULL,
    total_present INTEGER NOT NULL,
    last_updated VARCHAR(255) NOT NULL,
    ocd_id VARCHAR(255) NOT NULL,
    office VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    fax VARCHAR(255),
    state VARCHAR(255) NOT NULL,
    district INTEGER NOT NULL,
    at_large VARCHAR(255) NOT NULL,
    geoid INTEGER NOT NULL,
    missed_votes_pct NUMERIC(4, 2) NOT NULL,
    votes_with_party_pct NUMERIC(5, 2) NOT NULL,
    votes_against_party_pct NUMERIC(4, 2) NOT NULL
);